[package]
name = "drv-macros"
version = "0.4.1"
authors = ["Martin Algesten <martin@algesten.se>"]
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/algesten/drv"
homepage = "https://github.com/algesten/drv"
description = "Proc macros for drv"
readme = "README.md"
keywords = ["memoization", "incremental", "derive", "cache", "macro"]
categories = ["caching", "data-structures", "rust-patterns"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"

[lints]
workspace = true
